// g: "girl" | "boy" | "either"   style: classic | modern | nature | vintage | mythic
const NAMES = [
  // ── girls ──
  { n: "Amara", g: "girl", o: "Igbo", m: "grace", s: "modern" },
  { n: "Aurora", g: "girl", o: "Latin", m: "dawn", s: "classic" },
  { n: "Clara", g: "girl", o: "Latin", m: "bright, clear", s: "vintage" },
  { n: "Eloise", g: "girl", o: "French", m: "healthy, wide", s: "vintage" },
  { n: "Hazel", g: "girl", o: "English", m: "the hazel tree", s: "nature" },
  { n: "Iris", g: "girl", o: "Greek", m: "rainbow", s: "nature" },
  { n: "Isla", g: "girl", o: "Scottish", m: "island", s: "modern" },
  { n: "Juniper", g: "girl", o: "Latin", m: "the juniper tree", s: "nature" },
  { n: "Luna", g: "girl", o: "Latin", m: "moon", s: "modern" },
  { n: "Maya", g: "girl", o: "Sanskrit", m: "illusion, magic", s: "modern" },
  { n: "Nora", g: "girl", o: "Irish", m: "honor", s: "vintage" },
  { n: "Olive", g: "girl", o: "Latin", m: "the olive tree", s: "nature" },
  { n: "Penelope", g: "girl", o: "Greek", m: "weaver", s: "classic" },
  { n: "Rose", g: "girl", o: "Latin", m: "the rose flower", s: "classic" },
  { n: "Sofia", g: "girl", o: "Greek", m: "wisdom", s: "classic" },
  { n: "Violet", g: "girl", o: "Latin", m: "the violet flower", s: "vintage" },
  { n: "Willow", g: "girl", o: "English", m: "the willow tree", s: "nature" },
  { n: "Ananya", g: "girl", o: "Sanskrit", m: "unique, matchless", s: "modern" },
  { n: "Freya", g: "girl", o: "Norse", m: "lady; goddess of love", s: "mythic" },
  { n: "Ingrid", g: "girl", o: "Norse", m: "beautiful", s: "vintage" },
  { n: "Leilani", g: "girl", o: "Hawaiian", m: "heavenly flowers", s: "nature" },
  { n: "Mila", g: "girl", o: "Slavic", m: "gracious, dear", s: "modern" },
  { n: "Naomi", g: "girl", o: "Hebrew", m: "pleasantness", s: "classic" },
  { n: "Saoirse", g: "girl", o: "Irish", m: "freedom", s: "modern" },
  { n: "Yuki", g: "girl", o: "Japanese", m: "snow", s: "nature" },
  { n: "Priya", g: "girl", o: "Sanskrit", m: "beloved", s: "classic" },
  { n: "Esme", g: "girl", o: "French", m: "esteemed, loved", s: "vintage" },
  { n: "Daphne", g: "girl", o: "Greek", m: "laurel", s: "mythic" },
  { n: "Athena", g: "girl", o: "Greek", m: "goddess of wisdom", s: "mythic" },
  { n: "Matilda", g: "girl", o: "Germanic", m: "mighty in battle", s: "vintage" },
  { n: "Ada", g: "girl", o: "Germanic", m: "noble", s: "vintage" },
  { n: "Celeste", g: "girl", o: "Latin", m: "heavenly", s: "classic" },
  { n: "Ivy", g: "girl", o: "English", m: "the ivy plant", s: "nature" },
  { n: "Zara", g: "girl", o: "Arabic", m: "radiance, blooming", s: "modern" },
  { n: "Lucia", g: "girl", o: "Latin", m: "light", s: "classic" },
  { n: "Thea", g: "girl", o: "Greek", m: "goddess", s: "mythic" },

  // ── boys ──
  { n: "Arlo", g: "boy", o: "English", m: "fortified hill", s: "modern" },
  { n: "Atlas", g: "boy", o: "Greek", m: "to endure", s: "mythic" },
  { n: "Theodore", g: "boy", o: "Greek", m: "gift of God", s: "vintage" },
  { n: "Felix", g: "boy", o: "Latin", m: "lucky, happy", s: "classic" },
  { n: "Jasper", g: "boy", o: "Persian", m: "treasurer", s: "vintage" },
  { n: "Leo", g: "boy", o: "Latin", m: "lion", s: "classic" },
  { n: "Oscar", g: "boy", o: "Irish", m: "deer lover", s: "vintage" },
  { n: "Silas", g: "boy", o: "Latin", m: "of the forest", s: "nature" },
  { n: "Ezra", g: "boy", o: "Hebrew", m: "help", s: "classic" },
  { n: "Arjun", g: "boy", o: "Sanskrit", m: "bright, shining", s: "classic" },
  { n: "Mateo", g: "boy", o: "Spanish", m: "gift of God", s: "modern" },
  { n: "Finn", g: "boy", o: "Irish", m: "fair, bright", s: "modern" },
  { n: "Odin", g: "boy", o: "Norse", m: "chief of the Norse gods", s: "mythic" },
  { n: "Apollo", g: "boy", o: "Greek", m: "god of the sun and music", s: "mythic" },
  { n: "Rafael", g: "boy", o: "Hebrew", m: "God heals", s: "classic" },
  { n: "Hugo", g: "boy", o: "Germanic", m: "mind, intellect", s: "vintage" },
  { n: "August", g: "boy", o: "Latin", m: "great, venerable", s: "vintage" },
  { n: "Cyrus", g: "boy", o: "Persian", m: "sun", s: "classic" },
  { n: "Elio", g: "boy", o: "Italian", m: "sun", s: "modern" },
  { n: "Idris", g: "boy", o: "Welsh", m: "ardent lord", s: "modern" },
  { n: "Rohan", g: "boy", o: "Sanskrit", m: "ascending", s: "modern" },
  { n: "Thor", g: "boy", o: "Norse", m: "thunder", s: "mythic" },
  { n: "Oliver", g: "boy", o: "Latin", m: "the olive tree", s: "nature" },
  { n: "Kenji", g: "boy", o: "Japanese", m: "strong, healthy", s: "modern" },
  { n: "Henry", g: "boy", o: "Germanic", m: "ruler of the home", s: "classic" },
  { n: "Otto", g: "boy", o: "Germanic", m: "wealth", s: "vintage" },
  { n: "Bear", g: "boy", o: "English", m: "the bear", s: "nature" },
  { n: "Forrest", g: "boy", o: "English", m: "of the woods", s: "nature" },
  { n: "Julian", g: "boy", o: "Latin", m: "youthful", s: "classic" },
  { n: "Ronan", g: "boy", o: "Irish", m: "little seal", s: "nature" },
  { n: "Orion", g: "boy", o: "Greek", m: "the hunter constellation", s: "mythic" },
  { n: "Malik", g: "boy", o: "Arabic", m: "king", s: "classic" },

  // ── either ──
  { n: "Wren", g: "either", o: "English", m: "a small songbird", s: "nature" },
  { n: "Kai", g: "either", o: "Hawaiian", m: "sea", s: "modern" },
  { n: "Rowan", g: "either", o: "Irish", m: "little red one", s: "nature" },
  { n: "Sage", g: "either", o: "Latin", m: "wise", s: "nature" },
  { n: "River", g: "either", o: "English", m: "flowing water", s: "nature" },
  { n: "Phoenix", g: "either", o: "Greek", m: "the reborn firebird", s: "mythic" },
  { n: "Remy", g: "either", o: "French", m: "oarsman", s: "modern" },
  { n: "Quinn", g: "either", o: "Irish", m: "wisdom, counsel", s: "modern" },
  { n: "Ellis", g: "either", o: "Welsh", m: "benevolent", s: "vintage" },
  { n: "Ari", g: "either", o: "Hebrew", m: "lion", s: "modern" },
  { n: "Bodhi", g: "either", o: "Sanskrit", m: "enlightenment", s: "modern" },
  { n: "Indigo", g: "either", o: "Greek", m: "deep blue", s: "nature" },
  { n: "Avery", g: "either", o: "English", m: "ruler of elves", s: "classic" },
  { n: "Frankie", g: "either", o: "Latin", m: "free one", s: "vintage" },
];
